name: HomeGUI
version: 1.4
main: com.technovision.homegui.Homegui
api-version: 1.13
softdepend: [Essentials, EssentialsX]
authors: [TechnoVision]
commands:
  home:
    description: Opens the HomeGUI screen.
    usage: /<command>
    aliases: homes
  h:
    description: Reloads the HomeGUI config.
    usage: /<command>